---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monster
  name: monster
  namespace: monster
spec:
  replicas: 9
  selector:
    matchLabels:
      app: monster
  template:
    metadata:
      labels:
        app: monster
    spec:
      terminationGracePeriodSeconds: 4
      containers:
        - name: monster
          image: localhost:6200/lookinthelogs:cinq-kubedoom-2025
          imagePullPolicy: IfNotPresent
          env:
            - name: EMAIL
              value: diesel@dv.nl
            - name: USERNAME
              value: Diesel
            # PLS DONT USE SPACES IN YOUR USERNAME
            # FILL IN YOUR EMAIL AND USERNAME TO HAVE A CHANCE AT WINNING A PRIZE
          resources:
            requests:
              cpu: 10m
              memory: 16M
            limits:
              cpu: 10m
              memory: 16M

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/tmp/script2.sh"]
      nodeSelector:
        kubernetes.io/hostname: kubedoom-worker
