---
apiVersion: v1
kind: Service
metadata:
  name: score-service
spec:
  type: NodePort
  selector:
    app: score
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32001