---
apiVersion: v1
kind: Service
metadata:
  name: monster-service
  namespace: monster
spec:
  type: NodePort
  selector:
    app: monster
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000
